# Generated by Django 2.1.2 on 2018-11-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('stay_time', models.FloatField(default=0)),
                ('times', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('plans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Planner')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
