# Generated by Django 2.1.1 on 2018-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20181023_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='stay_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
