# Generated by Django 2.1.1 on 2018-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20181105_1040'),
    ]

    operations = [
        
    ]
