# Generated by Django 2.1.1 on 2018-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20181105_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
