# Generated by Django 2.1.2 on 2018-11-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20181106_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='stay_time',
        ),
        migrations.AddField(
            model_name='planner',
            name='duration',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='planner',
            name='spend_time',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
