# Generated by Django 2.1.2 on 2018-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20181116_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='id_plan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='planner',
            name='name_planner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
