# Generated by Django 2.1.2 on 2018-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20181120_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
