# Generated by Django 2.1.2 on 2018-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20181124_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='total_time',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
